--상품을 구매한 회원 비율 구하기

SELECT 
EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR,
EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH,
COUNT(A.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(B.USER_ID)/COUNT(A.USER_ID),1) AS PUCHASDE_RATIO
FROM (SELECT * FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021) A -- 2021년 회원가입한 회원
     , ONLINE_SALE B
WHERE A.USER_ID(+) = B.USER_ID
AND B.USER_ID IS NULL
GROUP BY EXTRACT(YEAR FROM B.SALES_DATE),EXTRACT(MONTH FROM B.SALES_DATE)
