-- FrontEnd 개발자 찾기
-- ID, 이메일, 이름, 성을 조회


--1.MySQl
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
WHERE A.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')  -- 비트 연산자
ORDER BY A.ID;

--2.Oracle
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
WHERE BITAND(A.SKILL_CODE, (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') !=0  -- 비트 연산자
ORDER BY A.ID;
