/*
3586. Find COVID Recovery Patients
*/

SELECT
    C1.PATIENT_ID,
    P.PATIENT_NAME,
    P.AGE,
    MIN(C2.TEST_DATE) - MIN(C1.TEST_DATE) AS RECOVERY_TIME
FROM COVID_TESTS C1
LEFT JOIN COVID_TESTS C2 ON C1.PATIENT_ID = C2.PATIENT_ID AND C2.RESULT = 'Negative'
LEFT JOIN PATIENTS P ON C1.PATIENT_ID = P.PATIENT_ID
WHERE 
    C1.RESULT = 'Positive' 
AND C1.TEST_DATE < C2.TEST_DATE
GROUP BY C1.PATIENT_ID, P.PATIENT_NAME, P.AGE
ORDER BY RECOVERY_TIME, P.PATIENT_NAME
